### ISSUE TITLE
AdaptyError (code null) . Error thrown null. Android. Release.

### ISSUE THREAD

**Issue by radomir9720** [adaptyteam/AdaptySDK-Flutter#30] opened 2021-11-16 18:37 UTC
Hi. I have have set up Adapty SDK and tested in debug with sandbox for android and ios. Everything worked well, as expected, but when i built a release, i started getting exceptions `AdaptyError (code null) . Error thrown null.`. In Profile mode everything works well.

The exception is thrown after calling `Adapty.identify()` and `Adapty.getPaywalls()`.

Tested on `Huawei P20 lite android 9`, and `Samsung Galaxy S9 android 9`.
<details>
<summary>Trace</summary>

```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: AdaptyError (code null) . Error thrown null.
       at Adapty._invokeMethodHandlingErrors(Adapty.java:242)
       at Adapty.getPaywalls(Adapty.java:64)
       at PurchaseBloc._purchase.<fn>(_purchase.java:79)
       at PurchaseBloc._tryCatchWrapper(PurchaseBloc.java:39)
       at PurchaseBloc._purchase(PurchaseBloc.java:76)
       at Bloc.on.<fn>.handleEvent(<fn>.java:456)
```
</details>

<details>
<summary>How i activate adapty</summary>

```dart
void main() {
  runZonedGuarded<void>(_run, CrashlyticsHelper.recordError);
}

Future<void> _run() async {
  WidgetsFlutterBinding.ensureInitialized();

  // FB
  await Firebase.initializeApp();

  final analytics = FirebaseAnalytics();
  await analytics.setAnalyticsCollectionEnabled(!kDebugMode);
  await analytics.logAppOpen();

  await DeviceInfoHelper.initialize();

  // error observers
  Bloc.observer = FirebaseBlocObserver();
  FlutterError.onError = CrashlyticsHelper.recordFlutterError;
  CrashlyticsHelper.log(DeviceInfoHelper.instance.infoMap.toString());  

  // Adapty
  Adapty.activate();
  // final installId = DeviceInfoHelper.instance.deviceId;
  // await Adapty.identify(installId);
  await Adapty.setLogLevel(AdaptyLogLevel.verbose);

  runApp();
}
```

</details>

**Comment by vladd-g** [comment] 2021-11-16 20:16
@radomir9720 hi, does it happen on the latest sdk version?

Actually I think it may be an obfuscation issue, since the sdk source code is not split to debug/release, and, as you said, everything worked well in debug

**Comment by radomir9720** [comment] 2021-11-17 05:29
Yes, it happens on latest `1.0.6` version.

**Comment by vladd-g** [comment] 2021-11-17 16:24
Does it reproduce stably in release? Do you use obfuscation?

**Comment by radomir9720** [comment] 2021-11-17 16:44
Yes, stably. And yes, i use obfuscation. In my app `build.gradle` in `buildTypes` i have set previously `minifyEnabled` and `shrinkResources` both to `true`. Now i tried to comment these lines, built a release apk, and still no positive result. Exact the same error.

**Comment by vladd-g** [comment] 2021-11-17 19:09
That's strange, we'll try to reproduce the problem.

Btw, do you have the following line in the proguard config?
`-keep class com.adapty.** { *; }`

**Comment by radomir9720** [comment] 2021-11-18 07:17
I don't have any proguard config at all, but i configured one, and the error persists.

**Comment by shok96** [comment] 2021-11-24 13:47
I do not use obfuscation and it also does not work for me in the release, in the debug mode everything is fine.

**Comment by shok96** [comment] 2021-12-01 05:07
I found the problem
nowhere is it written about this, I just had to compare the example code with my project
in new versions of flutter in the file.gradle file the following construction is written

subprojects {
     project.buildDir = "$ {rootProject.buildDir} / $ {project.name}"
     project.evaluationDependsOn (': app')
}

and in the example it is written like this

subprojects {
     project.buildDir = "$ {rootProject.buildDir} / $ {project.name}"
}
subprojects {
     project.evaluationDependsOn (': app')
}

after replacing the site as in the example, the subscriptions earned in the release.

**Comment by vladd-g** [comment] 2021-12-01 07:54
@shok96 cool, thank you, closing the issue

**Closed by vladd-g** 2021-12-01 07:54 UTC
